#!/usr/bin/env python3
"""
Emoji to Material Icons Replacement Script

This script replaces emojis with Material Icons throughout the E-Ticketing Revenue Estimator project.
Material Icons are more professional and consistent across different platforms.

Usage:
    python emoji_to_material_icons.py [--dry-run] [--revert]
"""

import os
import re
import argparse
import shutil
from pathlib import Path
from typing import Dict, List, Tuple

# Comprehensive emoji to Material Icons mapping
EMOJI_TO_MATERIAL_ICONS = {
    # Money and Finance
    ":material/attach_money:": ":material/attach_money:",
    ":material/payments:": ":material/payments:",
    ":material/credit_card:": ":material/credit_card:",
    ":material/diamond:": ":material/diamond:",
    ":material/money_off:": ":material/money_off:",
    
    # Charts and Analytics
    ":material/bar_chart:": ":material/bar_chart:",
    ":material/trending_up:": ":material/trending_up:",
    ":material/trending_down:": ":material/trending_down:",
    ":material/assignment:": ":material/assignment:",
    ":material/calendar_today:": ":material/calendar_today:",
    ":material/event:": ":material/event:",
    
    # Business and Office
    ":material/business:": ":material/business:",
    ":material/construction:": ":material/construction:",
    ":material/emoji_events:": ":material/emoji_events:",
    ":material/gps_fixed:": ":material/gps_fixed:",
    ":material/build:": ":material/build:",
    ":material/handyman:": ":material/handyman:",
    ":material/build:": ":material/build:",
    
    # Technology and Computing
    ":material/rocket_launch:": ":material/rocket_launch:",
    ":material/computer:": ":material/computer:",
    ":material/laptop:": ":material/laptop:",
    ":material/smartphone:": ":material/smartphone:",
    ":material/refresh:": ":material/refresh:",
    ":material/settings:": ":material/settings:",
    ":material/build:": ":material/build:",
    ":material/search:": ":material/search:",
    ":material/manage_search:": ":material/manage_search:",
    
    # Communication and Email
    ":material/email:": ":material/email:",
    ":material/mail:": ":material/mail:",
    ":material/forward_to_inbox:": ":material/forward_to_inbox:",
    ":material/outbox:": ":material/outbox:",
    ":material/inbox:": ":material/inbox:",
    ":material/phone:": ":material/phone:",
    ":material/fax:": ":material/fax:",
    
    # Storage and Database
    ":material/storage:": ":material/storage:",
    ":material/save:": ":material/save:",
    ":material/album:": ":material/album:",
    ":material/disc_full:": ":material/disc_full:",
    ":material/folder:": ":material/folder:",
    ":material/folder:": ":material/folder:",
    ":material/folder_open:": ":material/folder_open:",
    
    # Network and Cloud
    ":material/cloud:": ":material/cloud:",
    ":material/public:": ":material/public:",
    ":material/link:": ":material/link:",
    ":material/wifi:": ":material/wifi:",
    ":material/satellite:": ":material/satellite:",
    
    # Status and Alerts
    ":material/check_circle:": ":material/check_circle:",
    ":material/cancel:": ":material/cancel:",
    ":material/warning:": ":material/warning:",
    ":material/emergency:": ":material/emergency:",
    ":material/notifications:": ":material/notifications:",
    ":material/notifications_off:": ":material/notifications_off:",
    ":material/lightbulb:": ":material/lightbulb:",
    ":material/local_fire_department:": ":material/local_fire_department:",
    
    # Navigation and UI
    ":material/home:": ":material/home:",
    ":material/arrow_back:": ":material/arrow_back:",
    ":material/last_page:": ":material/last_page:",
    ":material/play_arrow:": ":material/play_arrow:",
    ":material/skip_next:": ":material/skip_next:",
    ":material/keyboard_arrow_up:": ":material/keyboard_arrow_up:",
    ":material/keyboard_arrow_down:": ":material/keyboard_arrow_down:",
    ":material/add:": ":material/add:",
    ":material/remove:": ":material/remove:",
    ":material/close:": ":material/close:",
    ":material/delete:": ":material/delete:",
    
    # Time and Calendar
    ":material/alarm:": ":material/alarm:",
    ":material/timer:": ":material/timer:",
    ":material/timer:": ":material/timer:",
    ":material/schedule:": ":material/schedule:",
    ":material/calendar_today:": ":material/calendar_today:",
    ":material/event:": ":material/event:",
    
    # Performance and Optimization
    ":material/flash_on:": ":material/flash_on:",
    ":material/battery_full:": ":material/battery_full:",
    ":material/signal_cellular_4_bar:": ":material/signal_cellular_4_bar:",
    ":material/tune:": ":material/tune:",
    ":material/equalizer:": ":material/equalizer:",
    
    # Security and Privacy
    ":material/lock:": ":material/lock:",
    ":material/lock_open:": ":material/lock_open:",
    ":material/key:": ":material/key:",
    ":material/security:": ":material/security:",
    ":material/visibility:": ":material/visibility:",
    ":material/search:": ":material/search:",
    
    # Entertainment and Events
    ":material/festival:": ":material/festival:",
    ":material/theater_comedy:": ":material/theater_comedy:",
    ":material/palette:": ":material/palette:",
    ":material/music_note:": ":material/music_note:",
    ":material/movie:": ":material/movie:",
    ":material/mic:": ":material/mic:",
    ":material/music_note:": ":material/music_note:",
    ":material/music_note:": ":material/music_note:",
    ":material/music_note:": ":material/music_note:",
    ":material/piano:": ":material/piano:",
    ":material/casino:": ":material/casino:",
    ":material/sports_bowling:": ":material/sports_bowling:",
    ":material/sports_esports:": ":material/sports_esports:",
    ":material/gps_fixed:": ":material/gps_fixed:",
    ":material/casino:": ":material/casino:",
    
    # Transportation
    ":material/directions_car:": ":material/directions_car:",
    ":material/local_taxi:": ":material/local_taxi:",
    ":material/directions_car:": ":material/directions_car:",
    ":material/directions_bus:": ":material/directions_bus:",
    ":material/directions_bus:": ":material/directions_bus:",
    ":material/directions_car:": ":material/directions_car:",
    ":material/local_police:": ":material/local_police:",
    ":material/local_hospital:": ":material/local_hospital:",
    ":material/local_fire_department:": ":material/local_fire_department:",
    ":material/directions_car:": ":material/directions_car:",
    ":material/directions_car:": ":material/directions_car:",
    ":material/local_shipping:": ":material/local_shipping:",
    ":material/local_shipping:": ":material/local_shipping:",
    ":material/agriculture:": ":material/agriculture:",
    ":material/two_wheeler:": ":material/two_wheeler:",
    ":material/two_wheeler:": ":material/two_wheeler:",
    ":material/directions_bike:": ":material/directions_bike:",
    ":material/electric_scooter:": ":material/electric_scooter:",
    ":material/flight:": ":material/flight:",
    ":material/flight:": ":material/flight:",
    ":material/flight:": ":material/flight:",
    ":material/rocket_launch:": ":material/rocket_launch:",
    ":material/flight:": ":material/flight:",
    ":material/directions_boat:": ":material/directions_boat:",
    ":material/sailing:": ":material/sailing:",
    ":material/directions_boat:": ":material/directions_boat:",
    ":material/directions_boat:": ":material/directions_boat:",
    ":material/directions_boat:": ":material/directions_boat:",
    ":material/train:": ":material/train:",
    ":material/train:": ":material/train:",
    ":material/train:": ":material/train:",
    ":material/train:": ":material/train:",
    ":material/train:": ":material/train:",
    ":material/subway:": ":material/subway:",
    ":material/train:": ":material/train:",
    ":material/train:": ":material/train:",
    ":material/tram:": ":material/tram:",
    ":material/train:": ":material/train:",
    ":material/train:": ":material/train:",
    ":material/tram:": ":material/tram:",
    ":material/train:": ":material/train:",
    ":material/train:": ":material/train:",
    ":material/cable_car:": ":material/cable_car:",
    ":material/cable_car:": ":material/cable_car:",
    ":material/train:": ":material/train:",
    
    # Buildings and Places
    ":material/home:": ":material/home:",
    ":material/house:": ":material/house:",
    ":material/business:": ":material/business:",
    ":material/business:": ":material/business:",
    ":material/business:": ":material/business:",
    ":material/local_hospital:": ":material/local_hospital:",
    ":material/account_balance:": ":material/account_balance:",
    ":material/atm:": ":material/atm:",
    ":material/hotel:": ":material/hotel:",
    ":material/hotel:": ":material/hotel:",
    ":material/store:": ":material/store:",
    ":material/school:": ":material/school:",
    ":material/store:": ":material/store:",
    ":material/factory:": ":material/factory:",
    ":material/celebration:": ":material/celebration:",
    ":material/temple_buddhist:": ":material/temple_buddhist:",
    ":material/castle:": ":material/castle:",
    ":material/tower:": ":material/tower:",
    ":material/account_balance:": ":material/account_balance:",
    ":material/church:": ":material/church:",
    ":material/mosque:": ":material/mosque:",
    ":material/temple_hindu:": ":material/temple_hindu:",
    ":material/synagogue:": ":material/synagogue:",
    ":material/temple_buddhist:": ":material/temple_buddhist:",
    ":material/mosque:": ":material/mosque:",
    
    # Nature and Weather
    ":material/wb_sunny:": ":material/wb_sunny:",
    ":material/partly_cloudy_day:": ":material/partly_cloudy_day:",
    ":material/cloud:": ":material/cloud:",
    ":material/grain:": ":material/grain:",
    ":material/grain:": ":material/grain:",
    ":material/thunderstorm:": ":material/thunderstorm:",
    ":material/thunderstorm:": ":material/thunderstorm:",
    ":material/ac_unit:": ":material/ac_unit:",
    ":material/ac_unit:": ":material/ac_unit:",
    ":material/ac_unit:": ":material/ac_unit:",
    ":material/ac_unit:": ":material/ac_unit:",
    ":material/air:": ":material/air:",
    ":material/air:": ":material/air:",
    ":material/tornado:": ":material/tornado:",
    ":material/cloud:": ":material/cloud:",
    ":material/waves:": ":material/waves:",
    ":material/water_drop:": ":material/water_drop:",
    ":material/water_drop:": ":material/water_drop:",
    ":material/umbrella:": ":material/umbrella:",
    ":material/flash_on:": ":material/flash_on:",
    ":material/local_fire_department:": ":material/local_fire_department:",
    ":material/explosion:": ":material/explosion:",
    ":material/ac_unit:": ":material/ac_unit:",
    ":material/star:": ":material/star:",
    ":material/star:": ":material/star:",
    ":material/auto_awesome:": ":material/auto_awesome:",
    ":material/auto_awesome:": ":material/auto_awesome:",
    ":material/nightlight:": ":material/nightlight:",
    ":material/nightlight:": ":material/nightlight:",
    ":material/nightlight:": ":material/nightlight:",
    ":material/nightlight:": ":material/nightlight:",
    ":material/nightlight:": ":material/nightlight:",
    ":material/wb_sunny:": ":material/wb_sunny:",
    
    # Food and Drink
    ":material/apple:": ":material/apple:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/eco:": ":material/eco:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/restaurant:": ":material/circle:",
    ":material/bakery_dining:": ":material/bakery_dining:",
    ":material/bakery_dining:": ":material/bakery_dining:",
    ":material/bakery_dining:": ":material/bakery_dining:",
    ":material/bakery_dining:": ":material/bakery_dining:",
    ":material/bakery_dining:": ":material/bakery_dining:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/lunch_dining:": ":material/lunch_dining:",
    ":material/lunch_dining:": ":material/lunch_dining:",
    ":material/local_pizza:": ":material/local_pizza:",
    ":material/lunch_dining:": ":material/lunch_dining:",
    ":material/lunch_dining:": ":material/lunch_dining:",
    ":material/lunch_dining:": ":material/lunch_dining:",
    ":material/lunch_dining:": ":material/lunch_dining:",
    ":material/lunch_dining:": ":material/lunch_dining:",
    ":material/lunch_dining:": ":material/lunch_dining:",
    ":material/lunch_dining:": ":material/lunch_dining:",
    ":material/egg:": ":material/egg:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/movie:": ":material/movie:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/ramen_dining:": ":material/ramen_dining:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/takeout_dining:": ":material/takeout_dining:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/icecream:": ":material/icecream:",
    ":material/icecream:": ":material/icecream:",
    ":material/icecream:": ":material/icecream:",
    ":material/donut_small:": ":material/donut_small:",
    ":material/cookie:": ":material/cookie:",
    ":material/cake:": ":material/cake:",
    ":material/cake:": ":material/cake:",
    ":material/cake:": ":material/cake:",
    ":material/pie_chart:": ":material/pie_chart:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/candy:": ":material/candy:",
    ":material/candy:": ":material/candy:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/baby_changing_station:": ":material/baby_changing_station:",
    ":material/local_drink:": ":material/local_drink:",
    ":material/local_cafe:": ":material/local_cafe:",
    ":material/local_cafe:": ":material/local_cafe:",
    ":material/local_cafe:": ":material/local_cafe:",
    ":material/local_bar:": ":material/local_bar:",
    ":material/celebration:": ":material/celebration:",
    ":material/wine_bar:": ":material/wine_bar:",
    ":material/local_bar:": ":material/local_bar:",
    ":material/local_bar:": ":material/local_bar:",
    ":material/sports_bar:": ":material/sports_bar:",
    ":material/sports_bar:": ":material/sports_bar:",
    ":material/celebration:": ":material/celebration:",
    ":material/local_bar:": ":material/local_bar:",
    ":material/local_drink:": ":material/local_drink:",
    ":material/local_drink:": ":material/local_drink:",
    ":material/local_drink:": ":material/local_drink:",
    ":material/local_drink:": ":material/local_drink:",
    ":material/ac_unit:": ":material/ac_unit:",
    
    # Activities and Sports
    ":material/sports_soccer:": ":material/sports_soccer:",
    ":material/sports_basketball:": ":material/sports_basketball:",
    ":material/sports_football:": ":material/sports_football:",
    ":material/sports_baseball:": ":material/sports_baseball:",
    ":material/sports_baseball:": ":material/sports_baseball:",
    ":material/sports_tennis:": ":material/sports_tennis:",
    ":material/sports_volleyball:": ":material/sports_volleyball:",
    ":material/sports_rugby:": ":material/sports_rugby:",
    ":material/sports:": ":material/sports:",
    ":material/sports_bar:": ":material/sports_bar:",
    ":material/toys:": ":material/toys:",
    ":material/sports_tennis:": ":material/sports_tennis:",
    ":material/sports_tennis:": ":material/sports_tennis:",
    ":material/sports_hockey:": ":material/sports_hockey:",
    ":material/sports_hockey:": ":material/sports_hockey:",
    ":material/sports:": ":material/sports:",
    ":material/sports:": ":material/sports:",
    ":material/sports:": ":material/sports:",
    ":material/sports:": ":material/sports:",
    ":material/golf_course:": ":material/golf_course:",
    ":material/kite:": ":material/kite:",
    ":material/sports:": ":material/sports:",
    ":material/phishing:": ":material/phishing:",
    ":material/scuba_diving:": ":material/scuba_diving:",
    ":material/sports_mma:": ":material/sports_mma:",
    ":material/sports_martial_arts:": ":material/sports_martial_arts:",
    ":material/sports:": ":material/sports:",
    ":material/skateboarding:": ":material/skateboarding:",
    ":material/roller_skating:": ":material/roller_skating:",
    ":material/sledding:": ":material/sledding:",
    ":material/ice_skating:": ":material/ice_skating:",
    ":material/sports:": ":material/sports:",
    ":material/downhill_skiing:": ":material/downhill_skiing:",
    ":material/downhill_skiing:": ":material/downhill_skiing:",
    ":material/snowboarding:": ":material/snowboarding:",
    ":material/paragliding:": ":material/paragliding:",
    ":material/fitness_center:": ":material/fitness_center:",
    ":material/sports_mma:": ":material/sports_mma:",
    ":material/sports_gymnastics:": ":material/sports_gymnastics:",
    ":material/sports_basketball:": ":material/sports_basketball:",
    ":material/sports:": ":material/sports:",
    ":material/sports_handball:": ":material/sports_handball:",
    ":material/golf_course:": ":material/golf_course:",
    ":material/sports:": ":material/sports:",
    ":material/self_improvement:": ":material/self_improvement:",
    ":material/surfing:": ":material/surfing:",
    ":material/pool:": ":material/pool:",
    ":material/sports:": ":material/sports:",
    ":material/rowing:": ":material/rowing:",
    ":material/climbing:": ":material/climbing:",
    ":material/directions_bike:": ":material/directions_bike:",
    ":material/directions_bike:": ":material/directions_bike:",
    ":material/emoji_events:": ":material/emoji_events:",
    ":material/workspace_premium:": ":material/workspace_premium:",
    ":material/workspace_premium:": ":material/workspace_premium:",
    ":material/workspace_premium:": ":material/workspace_premium:",
    ":material/military_tech:": ":material/military_tech:",
    ":material/military_tech:": ":material/military_tech:",
    ":material/local_florist:": ":material/local_florist:",
    ":material/volunteer_activism:": ":material/volunteer_activism:",
    ":material/confirmation_number:": ":material/confirmation_number:",
    ":material/local_activity:": ":material/local_activity:",
    ":material/festival:": ":material/festival:",
    ":material/sports:": ":material/sports:",
    ":material/theater_comedy:": ":material/theater_comedy:",
    ":material/sports:": ":material/sports:",
    ":material/palette:": ":material/palette:",
    ":material/movie:": ":material/movie:",
    ":material/mic:": ":material/mic:",
    ":material/headphones:": ":material/headphones:",
    ":material/music_note:": ":material/music_note:",
    ":material/music_note:": ":material/music_note:",
    ":material/music_note:": ":material/music_note:",
    ":material/piano:": ":material/piano:",
    ":material/music_note:": ":material/music_note:",
    ":material/music_note:": ":material/music_note:",
    ":material/music_note:": ":material/music_note:",
    ":material/music_note:": ":material/music_note:",
    ":material/music_note:": ":material/music_note:",
    ":material/music_note:": ":material/music_note:",
    ":material/music_note:": ":material/music_note:",
    ":material/casino:": ":material/casino:",
    ":material/sports:": ":material/sports:",
    ":material/gps_fixed:": ":material/gps_fixed:",
    ":material/sports_bowling:": ":material/sports_bowling:",
    ":material/sports_esports:": ":material/sports_esports:",
    ":material/casino:": ":material/casino:",
    ":material/extension:": ":material/extension:",
    
    # Objects and Tools
    ":material/watch:": ":material/watch:",
    ":material/smartphone:": ":material/smartphone:",
    ":material/smartphone:": ":material/smartphone:",
    ":material/laptop:": ":material/laptop:",
    ":material/keyboard:": ":material/keyboard:",
    ":material/computer:": ":material/computer:",
    ":material/print:": ":material/print:",
    ":material/mouse:": ":material/mouse:",
    ":material/mouse:": ":material/mouse:",
    ":material/sports_esports:": ":material/sports_esports:",
    ":material/compress:": ":material/compress:",
    ":material/save:": ":material/save:",
    ":material/save:": ":material/save:",
    ":material/album:": ":material/album:",
    ":material/disc_full:": ":material/disc_full:",
    ":material/videocam:": ":material/videocam:",
    ":material/photo_camera:": ":material/photo_camera:",
    ":material/photo_camera:": ":material/photo_camera:",
    ":material/videocam:": ":material/videocam:",
    ":material/movie:": ":material/movie:",
    ":material/movie:": ":material/movie:",
    ":material/phone:": ":material/phone:",
    ":material/phone:": ":material/phone:",
    ":material/pager:": ":material/pager:",
    ":material/fax:": ":material/fax:",
    ":material/tv:": ":material/tv:",
    ":material/radio:": ":material/radio:",
    ":material/mic:": ":material/mic:",
    ":material/equalizer:": ":material/equalizer:",
    ":material/tune:": ":material/tune:",
    ":material/explore:": ":material/explore:",
    ":material/timer:": ":material/timer:",
    ":material/timer:": ":material/timer:",
    ":material/alarm:": ":material/alarm:",
    ":material/schedule:": ":material/schedule:",
    ":material/hourglass_empty:": ":material/hourglass_empty:",
    ":material/hourglass_full:": ":material/hourglass_full:",
    ":material/wifi:": ":material/wifi:",
    ":material/battery_full:": ":material/battery_full:",
    ":material/power:": ":material/power:",
    ":material/lightbulb:": ":material/lightbulb:",
    ":material/flashlight_on:": ":material/flashlight_on:",
    ":material/local_fire_department:": ":material/local_fire_department:",
    ":material/local_fire_department:": ":material/local_fire_department:",
    ":material/local_fire_department:": ":material/local_fire_department:",
    ":material/oil_barrel:": ":material/oil_barrel:",
    ":material/money_off:": ":material/money_off:",
    ":material/payments:": ":material/payments:",
    ":material/payments:": ":material/payments:",
    ":material/payments:": ":material/payments:",
    ":material/payments:": ":material/payments:",
    ":material/paid:": ":material/paid:",
    ":material/attach_money:": ":material/attach_money:",
    ":material/credit_card:": ":material/credit_card:",
    ":material/diamond:": ":material/diamond:",
    ":material/balance:": ":material/balance:",
    ":material/construction:": ":material/construction:",
    ":material/handyman:": ":material/handyman:",
    ":material/construction:": ":material/construction:",
    ":material/build:": ":material/build:",
    ":material/handyman:": ":material/handyman:",
    ":material/handyman:": ":material/handyman:",
    ":material/build:": ":material/build:",
    ":material/construction:": ":material/construction:",
    ":material/construction:": ":material/construction:",
    ":material/construction:": ":material/construction:",
    ":material/settings:": ":material/settings:",
    ":material/pest_control:": ":material/pest_control:",
    ":material/attractions:": ":material/attractions:",
    ":material/sports:": ":material/sports:",
    ":material/warning:": ":material/warning:",
    ":material/warning:": ":material/warning:",
    ":material/construction:": ":material/construction:",
    ":material/restaurant:": ":material/restaurant:",
    ":material/sports:": ":material/sports:",
    ":material/sports:": ":material/sports:",
    ":material/security:": ":material/security:",
    ":material/smoking_rooms:": ":material/smoking_rooms:",
    ":material/sentiment_very_dissatisfied:": ":material/sentiment_very_dissatisfied:",
    ":material/sentiment_very_dissatisfied:": ":material/sentiment_very_dissatisfied:",
    ":material/sentiment_very_dissatisfied:": ":material/sentiment_very_dissatisfied:",
    ":material/museum:": ":material/museum:",
    ":material/auto_awesome:": ":material/auto_awesome:",
    ":material/circle:": ":material/circle:",
    ":material/remove_red_eye:": ":material/remove_red_eye:",
    ":material/content_cut:": ":material/content_cut:",
    ":material/science:": ":material/science:",
    ":material/telescope:": ":material/telescope:",
    ":material/biotech:": ":material/biotech:",
    ":material/circle:": ":material/circle:",
    ":material/healing:": ":material/healing:",
    ":material/medical_services:": ":material/medical_services:",
    ":material/medication:": ":material/medication:",
    ":material/vaccines:": ":material/vaccines:",
    ":material/bloodtype:": ":material/bloodtype:",
    ":material/biotech:": ":material/biotech:",
    ":material/coronavirus:": ":material/coronavirus:",
    ":material/biotech:": ":material/biotech:",
    ":material/science:": ":material/science:",
    ":material/device_thermostat:": ":material/device_thermostat:",
    ":material/cleaning_services:": ":material/cleaning_services:",
    ":material/shopping_basket:": ":material/shopping_basket:",
    ":material/cleaning_services:": ":material/cleaning_services:",
    ":material/cleaning_services:": ":material/cleaning_services:",
    ":material/cleaning_services:": ":material/cleaning_services:",
    ":material/content_cut:": ":material/content_cut:",
    ":material/local_pharmacy:": ":material/local_pharmacy:",
    ":material/notifications:": ":material/notifications:",
    ":material/key:": ":material/key:",
    ":material/key:": ":material/key:",
    ":material/door_front:": ":material/door_front:",
    ":material/chair:": ":material/chair:",
    ":material/bed:": ":material/bed:",
    ":material/weekend:": ":material/weekend:",
    ":material/mirror:": ":material/mirror:",
    ":material/shower:": ":material/shower:",
    ":material/bathtub:": ":material/bathtub:",
    ":material/pest_control:": ":material/pest_control:",
    ":material/toys:": ":material/toys:",
    ":material/toys:": ":material/toys:",
    ":material/image:": ":material/image:",
    ":material/window:": ":material/window:",
    ":material/shopping_bag:": ":material/shopping_bag:",
    ":material/card_giftcard:": ":material/card_giftcard:",
    ":material/card_giftcard:": ":material/card_giftcard:",
    ":material/celebration:": ":material/celebration:",
    ":material/celebration:": ":material/celebration:",
    ":material/celebration:": ":material/celebration:",
    ":material/celebration:": ":material/celebration:",
    ":material/celebration:": ":material/celebration:",
    ":material/card_giftcard:": ":material/card_giftcard:",
    ":material/card_giftcard:": ":material/card_giftcard:",
    ":material/volunteer_activism:": ":material/volunteer_activism:",
    ":material/local_activity:": ":material/local_activity:",
    ":material/confirmation_number:": ":material/confirmation_number:",
    ":material/military_tech:": ":material/military_tech:",
    ":material/emoji_events:": ":material/emoji_events:",
    ":material/military_tech:": ":material/military_tech:",
    ":material/workspace_premium:": ":material/workspace_premium:",
    ":material/workspace_premium:": ":material/workspace_premium:",
    ":material/workspace_premium:": ":material/workspace_premium:",
    ":material/sports_soccer:": ":material/sports_soccer:",
    ":material/sports_basketball:": ":material/sports_basketball:",
    ":material/sports_football:": ":material/sports_football:",
    ":material/sports_baseball:": ":material/sports_baseball:",
    ":material/sports_baseball:": ":material/sports_baseball:",
    ":material/sports_tennis:": ":material/sports_tennis:",
    ":material/sports_volleyball:": ":material/sports_volleyball:",
    ":material/sports_rugby:": ":material/sports_rugby:",
    ":material/sports:": ":material/sports:",
    ":material/sports_bar:": ":material/sports_bar:",
    ":material/toys:": ":material/toys:",
    ":material/sports_tennis:": ":material/sports_tennis:",
    ":material/sports_tennis:": ":material/sports_tennis:",
    ":material/sports_hockey:": ":material/sports_hockey:",
    ":material/sports_hockey:": ":material/sports_hockey:",
    ":material/sports:": ":material/sports:",
    ":material/sports:": ":material/sports:",
    ":material/sports:": ":material/sports:",
    ":material/sports:": ":material/sports:",
    ":material/golf_course:": ":material/golf_course:",
    ":material/kite:": ":material/kite:",
    ":material/sports:": ":material/sports:",
    ":material/phishing:": ":material/phishing:",
    ":material/scuba_diving:": ":material/scuba_diving:",
    ":material/sports_mma:": ":material/sports_mma:",
    ":material/sports_martial_arts:": ":material/sports_martial_arts:",
    ":material/sports:": ":material/sports:",
    ":material/skateboarding:": ":material/skateboarding:",
    ":material/roller_skating:": ":material/roller_skating:",
    ":material/sledding:": ":material/sledding:",
    ":material/ice_skating:": ":material/ice_skating:",
    ":material/sports:": ":material/sports:",
    ":material/downhill_skiing:": ":material/downhill_skiing:",
    ":material/downhill_skiing:": ":material/downhill_skiing:",
    ":material/snowboarding:": ":material/snowboarding:",
    ":material/paragliding:": ":material/paragliding:",
    ":material/fitness_center:": ":material/fitness_center:",
    ":material/sports_mma:": ":material/sports_mma:",
    ":material/sports_gymnastics:": ":material/sports_gymnastics:",
    ":material/sports_basketball:": ":material/sports_basketball:",
    ":material/sports:": ":material/sports:",
    ":material/sports_handball:": ":material/sports_handball:",
    ":material/golf_course:": ":material/golf_course:",
    ":material/sports:": ":material/sports:",
    ":material/self_improvement:": ":material/self_improvement:",
    ":material/surfing:": ":material/surfing:",
    ":material/pool:": ":material/pool:",
    ":material/sports:": ":material/sports:",
    ":material/rowing:": ":material/rowing:",
    ":material/climbing:": ":material/climbing:",
    ":material/directions_bike:": ":material/directions_bike:",
    ":material/directions_bike:": ":material/directions_bike:",
    
    # Symbols and Shapes
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite_border:": ":material/favorite_border:",
    ":material/favorite:": ":material/favorite:",
    ":material/heart_broken:": ":material/heart_broken:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/favorite:": ":material/favorite:",
    ":material/card_giftcard:": ":material/card_giftcard:",
    ":material/favorite:": ":material/favorite:",
    ":material/peace:": ":material/peace:",
    ":material/church:": ":material/church:",
    ":material/mosque:": ":material/mosque:",
    ":material/temple_hindu:": ":material/temple_hindu:",
    ":material/temple_buddhist:": ":material/temple_buddhist:",
    ":material/synagogue:": ":material/synagogue:",
    ":material/star:": ":material/star:",
    ":material/synagogue:": ":material/synagogue:",
    ":material/yin_yang:": ":material/yin_yang:",
    ":material/church:": ":material/church:",
    ":material/place_of_worship:": ":material/place_of_worship:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/horoscope:": ":material/horoscope:",
    ":material/badge:": ":material/badge:",
    ":material/science:": ":material/science:",
    ":material/check_circle:": ":material/check_circle:",
    ":material/warning:": ":material/warning:",
    ":material/warning:": ":material/warning:",
    ":material/mobile_off:": ":material/mobile_off:",
    ":material/vibration:": ":material/vibration:",
    ":material/paid:": ":material/paid:",
    ":material/free_cancellation:": ":material/free_cancellation:",
    ":material/approval:": ":material/approval:",
    ":material/business:": ":material/business:",
    ":material/calendar_month:": ":material/calendar_month:",
    ":material/star:": ":material/star:",
    ":material/compare:": ":material/compare:",
    ":material/local_florist:": ":material/local_florist:",
    ":material/discount:": ":material/discount:",
    ":material/lock:": ":material/lock:",
    ":material/celebration:": ":material/celebration:",
    ":material/approval:": ":material/approval:",
    ":material/fullscreen:": ":material/fullscreen:",
    ":material/discount:": ":material/discount:",
    ":material/block:": ":material/block:",
    ":material/text_fields:": ":material/text_fields:",
    ":material/text_fields:": ":material/text_fields:",
    ":material/text_fields:": ":material/text_fields:",
    ":material/clear:": ":material/clear:",
    ":material/radio_button_unchecked:": ":material/radio_button_unchecked:",
    ":material/emergency:": ":material/emergency:",
    ":material/cancel:": ":material/cancel:",
    ":material/cancel:": ":material/cancel:",
    ":material/stop:": ":material/stop:",
    ":material/block:": ":material/block:",
    ":material/badge:": ":material/badge:",
    ":material/block:": ":material/block:",
    ":material/verified:": ":material/verified:",
    ":material/sentiment_very_dissatisfied:": ":material/sentiment_very_dissatisfied:",
    ":material/hot_tub:": ":material/hot_tub:",
    ":material/no_pedestrians:": ":material/no_pedestrians:",
    ":material/do_not_disturb:": ":material/do_not_disturb:",
    ":material/no_cycling:": ":material/no_cycling:",
    ":material/no_drinks:": ":material/no_drinks:",
    ":material/block:": ":material/block:",
    ":material/mobile_off:": ":material/mobile_off:",
    ":material/smoke_free:": ":material/smoke_free:",
    ":material/priority_high:": ":material/priority_high:",
    ":material/priority_high:": ":material/priority_high:",
    ":material/help:": ":material/help:",
    ":material/help:": ":material/help:",
    ":material/priority_high:": ":material/priority_high:",
    ":material/help:": ":material/help:",
    ":material/brightness_low:": ":material/brightness_low:",
    ":material/brightness_high:": ":material/brightness_high:",
    ":material/graphic_eq:": ":material/graphic_eq:",
    ":material/warning:": ":material/warning:",
    ":material/school:": ":material/school:",
    ":material/anchor:": ":material/anchor:",
    ":material/local_florist:": ":material/local_florist:",
    ":material/new_releases:": ":material/new_releases:",
    ":material/recycling:": ":material/recycling:",
    ":material/check_circle:": ":material/check_circle:",
    ":material/location_on:": ":material/location_on:",
    ":material/trending_up:": ":material/trending_up:",
    ":material/auto_awesome:": ":material/auto_awesome:",
    ":material/auto_awesome:": ":material/auto_awesome:",
    ":material/cancel:": ":material/cancel:",
    ":material/public:": ":material/public:",
    ":material/diamond:": ":material/diamond:",
    ":material/subway:": ":material/subway:",
    ":material/cyclone:": ":material/cyclone:",
    ":material/bedtime:": ":material/bedtime:",
    ":material/atm:": ":material/atm:",
    ":material/wc:": ":material/wc:",
    ":material/accessible:": ":material/accessible:",
    ":material/local_parking:": ":material/local_parking:",
    ":material/check_box_outline_blank:": ":material/check_box_outline_blank:",
    ":material/language:": ":material/language:",
    ":material/passport:": ":material/passport:",
    ":material/luggage:": ":material/luggage:",
    ":material/luggage:": ":material/luggage:",
    ":material/luggage:": ":material/luggage:",
    ":material/man:": ":material/man:",
    ":material/woman:": ":material/woman:",
    ":material/baby_changing_station:": ":material/baby_changing_station:",
    ":material/wc:": ":material/wc:",
    ":material/delete:": ":material/delete:",
    ":material/movie:": ":material/movie:",
    ":material/signal_cellular_4_bar:": ":material/signal_cellular_4_bar:",
    ":material/language:": ":material/language:",
    ":material/text_fields:": ":material/text_fields:",
    ":material/info:": ":material/info:",
    ":material/text_fields:": ":material/text_fields:",
    ":material/text_fields:": ":material/text_fields:",
    ":material/text_fields:": ":material/text_fields:",
    ":material/cancel:": ":material/cancel:",
    ":material/check_circle:": ":material/check_circle:",
    ":material/trending_up:": ":material/trending_up:",
    ":material/ac_unit:": ":material/ac_unit:",
    ":material/new_releases:": ":material/new_releases:",
    ":material/free_cancellation:": ":material/free_cancellation:",
    ":material/looks_one:": ":material/looks_one:",
    ":material/looks_one:": ":material/looks_one:",
    ":material/looks_two:": ":material/looks_two:",
    ":material/looks_3:": ":material/looks_3:",
    ":material/looks_4:": ":material/looks_4:",
    ":material/looks_5:": ":material/looks_5:",
    ":material/looks_6:": ":material/looks_6:",
    ":material/filter_7:": ":material/filter_7:",
    ":material/filter_8:": ":material/filter_8:",
    ":material/filter_9:": ":material/filter_9:",
    ":material/filter_9_plus:": ":material/filter_9_plus:",
    ":material/pin:": ":material/pin:",
    ":material/tag:": ":material/tag:",
    ":material/star:": ":material/star:",
    ":material/eject:": ":material/eject:",
    ":material/play_arrow:": ":material/play_arrow:",
    ":material/pause:": ":material/pause:",
    ":material/play_pause:": ":material/play_pause:",
    ":material/stop:": ":material/stop:",
    ":material/fiber_manual_record:": ":material/fiber_manual_record:",
    ":material/skip_next:": ":material/skip_next:",
    ":material/skip_previous:": ":material/skip_previous:",
    ":material/fast_forward:": ":material/fast_forward:",
    ":material/fast_rewind:": ":material/fast_rewind:",
    ":material/keyboard_double_arrow_up:": ":material/keyboard_double_arrow_up:",
    ":material/keyboard_double_arrow_down:": ":material/keyboard_double_arrow_down:",
    ":material/arrow_back:": ":material/arrow_back:",
    ":material/keyboard_arrow_up:": ":material/keyboard_arrow_up:",
    ":material/keyboard_arrow_down:": ":material/keyboard_arrow_down:",
    ":material/arrow_forward:": ":material/arrow_forward:",
    ":material/arrow_back:": ":material/arrow_back:",
    ":material/arrow_upward:": ":material/arrow_upward:",
    ":material/arrow_downward:": ":material/arrow_downward:",
    ":material/north_east:": ":material/north_east:",
    ":material/south_east:": ":material/south_east:",
    ":material/south_west:": ":material/south_west:",
    ":material/north_west:": ":material/north_west:",
    ":material/swap_vert:": ":material/swap_vert:",
    ":material/swap_horiz:": ":material/swap_horiz:",
    ":material/subdirectory_arrow_left:": ":material/subdirectory_arrow_left:",
    ":material/reply:": ":material/reply:",
    ":material/arrow_upward:": ":material/arrow_upward:",
    ":material/arrow_downward:": ":material/arrow_downward:",
    ":material/shuffle:": ":material/shuffle:",
    ":material/repeat:": ":material/repeat:",
    ":material/repeat_one:": ":material/repeat_one:",
    ":material/refresh:": ":material/refresh:",
    ":material/refresh:": ":material/refresh:",
    ":material/music_note:": ":material/music_note:",
    ":material/music_note:": ":material/music_note:",
    ":material/add:": ":material/add:",
    ":material/remove:": ":material/remove:",
    ":material/calculate:": ":material/calculate:",
    ":material/close:": ":material/close:",
    ":material/all_inclusive:": ":material/all_inclusive:",
    ":material/attach_money:": ":material/attach_money:",
    ":material/currency_exchange:": ":material/currency_exchange:",
    ":material/copyright:": ":material/copyright:",
    ":material/copyright:": ":material/copyright:",
    ":material/copyright:": ":material/copyright:",
    ":material/graphic_eq:": ":material/graphic_eq:",
    ":material/all_inclusive:": ":material/all_inclusive:",
    ":material/all_inclusive:": ":material/all_inclusive:",
    ":material/last_page:": ":material/last_page:",
    ":material/arrow_back:": ":material/arrow_back:",
    ":material/play_arrow:": ":material/play_arrow:",
    ":material/keyboard_arrow_up:": ":material/keyboard_arrow_up:",
    ":material/skip_next:": ":material/skip_next:",
    ":material/check:": ":material/check:",
    ":material/check_box:": ":material/check_box:",
    ":material/radio_button_checked:": ":material/radio_button_checked:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/circle:": ":material/circle:",
    ":material/radio_button_unchecked:": ":material/radio_button_unchecked:",
    ":material/circle:": ":material/circle:",
    ":material/change_history:": ":material/change_history:",
    ":material/change_history:": ":material/change_history:",
    ":material/diamond:": ":material/diamond:",
    ":material/diamond:": ":material/diamond:",
    ":material/diamond:": ":material/diamond:",
    ":material/diamond:": ":material/diamond:",
    ":material/check_box_outline_blank:": ":material/check_box_outline_blank:",
    ":material/check_box:": ":material/check_box:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/stop:": ":material/stop:",
    ":material/volume_mute:": ":material/volume_mute:",
    ":material/volume_off:": ":material/volume_off:",
    ":material/volume_down:": ":material/volume_down:",
    ":material/volume_up:": ":material/volume_up:",
    ":material/notifications:": ":material/notifications:",
    ":material/notifications_off:": ":material/notifications_off:",
    ":material/campaign:": ":material/campaign:",
    ":material/campaign:": ":material/campaign:",
    ":material/visibility:": ":material/visibility:",
    ":material/chat:": ":material/chat:",
    ":material/chat_bubble:": ":material/chat_bubble:",
    ":material/chat:": ":material/chat:",
    ":material/casino:": ":material/casino:",
    ":material/casino:": ":material/casino:",
    ":material/favorite:": ":material/favorite:",
    ":material/diamond:": ":material/diamond:",
    ":material/casino:": ":material/casino:",
    ":material/casino:": ":material/casino:",
    ":material/casino:": ":material/casino:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
    ":material/schedule:": ":material/schedule:",
}

def find_python_files(directory: Path) -> List[Path]:
    """Find all Python files in the directory"""
    python_files = []
    for file_path in directory.rglob("*.py"):
        # Skip __pycache__, .git, and venv directories
        if ("__pycache__" not in str(file_path) and 
            ".git" not in str(file_path) and 
            "venv" not in str(file_path) and
            "site-packages" not in str(file_path)):
            python_files.append(file_path)
    return python_files

def backup_file(file_path: Path) -> Path:
    """Create a backup of the file"""
    backup_path = file_path.with_suffix(file_path.suffix + ".emoji_backup")
    shutil.copy2(file_path, backup_path)
    return backup_path

def replace_emojis_in_file(file_path: Path, dry_run: bool = False) -> Tuple[int, List[str]]:
    """Replace emojis with Material Icons in a single file"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original_content = content
        replacements_made = []
        
        # Replace emojis with Material Icons
        for emoji, material_icon in EMOJI_TO_MATERIAL_ICONS.items():
            if emoji in content:
                # Count occurrences
                count = content.count(emoji)
                if count > 0:
                    content = content.replace(emoji, material_icon)
                    replacements_made.append(f"  {emoji} → {material_icon} ({count} times)")
        
        # Write back to file if not dry run and changes were made
        if not dry_run and content != original_content:
            # Create backup first
            backup_file(file_path)
            
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
        
        return len(replacements_made), replacements_made
    
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return 0, []

def revert_file(file_path: Path) -> bool:
    """Revert a file from its backup"""
    backup_path = file_path.with_suffix(file_path.suffix + ".emoji_backup")
    
    if backup_path.exists():
        shutil.copy2(backup_path, file_path)
        backup_path.unlink()  # Remove backup file
        return True
    return False

def main():
    parser = argparse.ArgumentParser(description="Replace emojis with Material Icons in Python files")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be changed without making changes")
    parser.add_argument("--revert", action="store_true", help="Revert all files from backups")
    parser.add_argument("--directory", default=".", help="Directory to process (default: current directory)")
    
    args = parser.parse_args()
    
    project_dir = Path(args.directory)
    
    if not project_dir.exists():
        print(f"Error: Directory {project_dir} does not exist")
        return 1
    
    # Find all Python files
    python_files = find_python_files(project_dir)
    
    if not python_files:
        print("No Python files found in the directory")
        return 0
    
    print(f"Found {len(python_files)} Python files to process")
    
    if args.revert:
        print("\n:material/refresh: Reverting files from backups...")
        reverted_count = 0
        
        for file_path in python_files:
            if revert_file(file_path):
                print(f":material/check_circle: Reverted: {file_path}")
                reverted_count += 1
        
        print(f"\n:material/bar_chart: Summary: Reverted {reverted_count} files")
        return 0
    
    # Process files
    total_replacements = 0
    files_changed = 0
    
    action = "Would replace" if args.dry_run else "Replacing"
    print(f"\n:material/refresh: {action} emojis with Material Icons...")
    
    for file_path in python_files:
        replacement_count, replacements = replace_emojis_in_file(file_path, args.dry_run)
        
        if replacement_count > 0:
            files_changed += 1
            total_replacements += replacement_count
            
            print(f"\n📄 {file_path}:")
            for replacement in replacements:
                print(replacement)
    
    # Summary
    print(f"\n:material/bar_chart: Summary:")
    print(f"  Files processed: {len(python_files)}")
    print(f"  Files with changes: {files_changed}")
    print(f"  Total emoji types replaced: {total_replacements}")
    
    if args.dry_run:
        print(f"\n:material/lightbulb: This was a dry run. To apply changes, run without --dry-run")
        print(f":material/lightbulb: To revert changes later, use --revert")
    else:
        print(f"\n:material/check_circle: Emoji replacement complete!")
        print(f":material/save: Backup files created with .emoji_backup extension")
        print(f":material/refresh: To revert changes, run: python {__file__} --revert")
    
    return 0

if __name__ == "__main__":
    exit(main()) 